### ISSUE TITLE
支持 Fresns 音频 和 文档 处理规则

### ISSUE THREAD

**Issue by Naruto2018** [ExerciseBook/fresns-imagex#14]
上次那个BUG后，新上传的文档和音频 防盗链地址有问题 因为缺少  tos-cn-i-pxllsppmpg

**Comment by Naruto2018** [comment]
对比了下 文档 和 音频 地址
缺少 tos-cn-i-pxllsppmpg

**Comment by Naruto2018** [comment]
音频防盗链缺少 tos-cn-i-pxllsppmpg

**Comment by ExerciseBook** [comment]
2004 错误，不是 4404 错误，和我没关系。检查一下是不是没设模板。
我在文档里提到了，需要给音频添加一个获取原图的模板，而不能留空。
如果留空的话，需要在 imagex 控制台里允许源地址访问。
